### ISSUE TITLE
New skill : Google search query : Client : All

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_skill_data#107]
**Actual Behaviour**

Add skill by which user can ask susi to google search anything

**Action type required**

may be "googlesearch"

**Useful for**

All client

**Comment by amitiwary999** [comment]
@chiragw15  webSearch action type is different ?

**Comment by chiragw15** [comment]
No need for this. We have websearch. It is same.

**Comment by amitiwary999** [comment]
then closing this issue.
