### ISSUE TITLE
Knowledge: Name the founders of the world top technology companies 

### ISSUE THREAD

**Issue by hpdang** [fossasia/susi_skill_data#118]
**Actual Behaviour**

Susi can't name famous people in tech industry. 

Sample questions: who is the founder of Google/Apple/Facebook/Uber etc.? Name the founder of..... ? can you tell me who is the founder of .....? Who is the father of....? etc.

**Expected Behaviour**

Susi is able to name founders of the world top companies and maybe a link to his/her wikipedia article. If susi doesn't have the answer, please suggestion for something else for instance: I am not sure about it, but I know the founder of ... is ....

**Comment by saurabhjn76** [comment]
![image](https://user-images.githubusercontent.com/9781788/27067135-d1eedbfe-5026-11e7-969a-d30f7cb27cce.png)
I have written a dream [http://dream.susi.ai/p/founder](http://dream.susi.ai/p/founder), but facing problems while generalizing things, it would be great if @dynamitechetan,@jyoth1raditya, @DravitLochan, @AliAyub007 could help me with it.

**Comment by DravitLochan** [comment]
There is this problem that the API is sending response if the first character is capital.

**Comment by saurabhjn76** [comment]
Thanks, @DravitLochan :+1: , would resolve it soon.
