### ISSUE TITLE
Knowledge: Improve answers to any weather related questions or statements 

### ISSUE THREAD

**Issue by hpdang** [fossasia/susi_skill_data#122]
**Actual Behaviour**

There is already a weather skill. However Susi doesn't seem to give accurate answers. https://github.com/fossasia/susi_skill_data/blob/master/models/general/knowledge/en/weather_information.txt

![screen shot 2017-06-09 at 7 26 51 pm](https://user-images.githubusercontent.com/1658742/26986891-b7a77cb8-4d49-11e7-8182-114fdbbf14f1.png)

![screen shot 2017-06-09 at 3 33 34 pm](https://user-images.githubusercontent.com/1658742/26986922-cff30706-4d49-11e7-855a-9d587a7a7bc6.png)

**Expected Behaviour**
Susi is mastering in any weather related topic 

**Steps to reproduce it**
- Test what Susi is/isn't able to answer when it comes to weather 
- Think of all possible questions or statements related to weather 
- Think of fixed answers, random answers and answers retrieved from a datasource
- You can break this issue into smaller issues if needed.

**Comment by AliAyub007** [comment]
@hpdang As this is complete we can close this issue now.
