### ISSUE TITLE
Susi is giving a non-human answer to the question 'What is your name' 

### ISSUE THREAD

**Issue by hpdang** [fossasia/susi_skill_data#126]
**Actual Behaviour**

Once user types what is your name? 
Susi answers: your name is a 2017 Japanese movie by Shinkai Makoto. 
This answer is correct but user wants to know if susi can tell her name 

**Expected Behaviour**
- My name is Susi.  

**Steps to reproduce it**
- find out where susi get the answer for that question and fix it

**Comment by madhavrathi** [comment]
@hpdang Will work on this.
