### ISSUE TITLE
adding a new genre of skills - tutorials

### ISSUE THREAD

**Issue by DravitLochan** [fossasia/susi_skill_data#133]
**Actual Behaviour**
To make Susi better, let us have a new genre of skills called "tutorial". Adding it will be a whole new turn to Susi skills. Before opening this issue I did some research to try to find a single API which could return rules (tutorial) for the game passed in as a parameter but could not find it. Though APIs for individual games were available and could be even implemented easily.

**Expected Behaviour**
It would be nice to have a seperate genre of skills. This can include separate skills for tutorial/rules of chess, carrom, pool, Chinese Checkers, cricket, basketball, football etc etc. Not just games but traffic rules, driving rules, traffic signals, etc etc.

**Steps to reproduce it**
Make a folder for such skills.

**Would you like to work on the issue?**
Yes. Would also try to add some cool skills.

**Comment by mariobehling** [comment]
This is a core feature of SUSI and exactly the intended way, that SUSI can be a teacher. I don't see any request for a feature or requirement to implement code. We already have a way to make conversations. It needs to be documented more though. As you are not requesting a feature or reporting a bug I am closing this.
