### ISSUE TITLE
Add the complete Ferengi Rules of Acquisition

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_data#156]
Questions could be:
* What are the Ferengi Rules of Acquisition.. They are this and that. Rule 1 is.. Rule 2 is..
* What is rule 42 of the Ferengi Rules Of Acquisition. Rule 42 of the Ferengi Rules Of Acquisition is...

**Comment by Laughing-Boy** [comment]
Can I work on it

**Comment by hpdang** [comment]
@dynamitechetan can you help Aditya with this?

**Comment by dynamitechetan** [comment]
sure 👍
