### ISSUE TITLE
Create user_negative_expression skill 

### ISSUE THREAD

**Issue by hpdang** [fossasia/susi_skill_data#186]
**Actual Behaviour**

SUSI is unable to respond to negative expression like: I am unhappy, I am hungry, I am sick, I am stupid, you are stupid, you are not so smart, you are fake, this is bullshit etc. 

**Expected Behaviour**

Answer to negative expressions in a positive, fun manner 

**Steps to reproduce it**
create user_negative_expression skill, refer to  https://github.com/fossasia/susi_skill_data/blob/master/models/general/smalltalk/en/user_positive_expression.txt

**Comment by dynamitechetan** [comment]
please assign me this issue.
