### ISSUE TITLE
Add examples to ALL skills

### ISSUE THREAD

**Issue by uday96** [fossasia/susi_skill_data#192]
**Actual Behaviour**

Skills don't have examples as of now

**Expected Behaviour**

**ALL** skills must have examples. This helps us know what susi can do.

There is a very simple technique to do that now:
1.) add an ‚!example:‘ bang line inside of a skill. See here how to do that: fossasia/susi_skill_data@40f0c43
2.) check  http://api.susi.ai/cms/getExampleSkill.json and see if your example is inside

Everyone can contribute for this.

**Comment by rishiraj824** [comment]
:+1:  ok I will proceed with adding examples to https://github.com/fossasia/susi_skill_data/tree/master/models/general/problemsolving/
and 
https://github.com/fossasia/susi_skill_data/tree/master/models/general/assistants

**Comment by uday96** [comment]
I'll add examples for all https://github.com/fossasia/susi_skill_data/tree/master/models/general/knowledge/en

**Comment by madhavrathi** [comment]
@uday96 I will add examples for all entertainment

**Comment by Laughing-Boy** [comment]
I will add the examples for problem solving
