### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_skill_data#2]
..from https://github.com/fossasia/susi_server/tree/development/docs/skills

**Comment by madhavrathi** [comment]
@Orbiter hey, i made the documentation for different cases of value of path for different JSON patterns(that you provided). Should i send them here in markdown format or .txt
Thanks

**Comment by mariobehling** [comment]
Markdown please in the /docs folder I think.

**Comment by madhavrathi** [comment]
@mariobehling I have added the tutorial in the original doc. Please review.
Thanks.

**Comment by Orbiter** [comment]
done
