### ISSUE TITLE
The table type output doesn't show "number" type of outputs

### ISSUE THREAD

**Issue by Manveer695** [fossasia/susi_skill_data#212]
**Actual Behaviour**
The table type output data is not able to show numbers as an output

**Screenshots of the issue**
The skill:
<img width="507" alt="numberissue" src="https://user-images.githubusercontent.com/20307535/27817200-8129890c-60ad-11e7-84c4-062e6acb36f6.PNG">
The SUSI output:
<img width="452" alt="numberissue2" src="https://user-images.githubusercontent.com/20307535/27817215-993219a6-60ad-11e7-8668-eb8a35dcf8e7.PNG">

The endpoint output:
![inkednumissue3](https://user-images.githubusercontent.com/20307535/27817221-a340df7c-60ad-11e7-8320-402bb94070e4.jpg)

**Would you like to work on the issue?**
@Orbiter Please look into the issue sir. I have tried with other number values too but no output sir. Thank you for the help.

**Comment by Orbiter** [comment]
ok that ist for sure a problem in the client. The client expects a string but gets a number. I believe it should be easy to fix that in the table renderer: please turn to that development team and make an issue to get that fixed.
