### ISSUE TITLE
Add description to all the skills

### ISSUE THREAD

**Issue by saurabhjn76** [fossasia/susi_skill_data#234]
To build skill page, add a description to each skill.

**Comment by saurabhjn76** [comment]
I will add description in entertainment skills

**Comment by dynamitechetan** [comment]
I will add for knowledge category.

**Comment by DravitLochan** [comment]
I will add on assistant, problem solving, shopping and small talks

**Comment by madhavrathi** [comment]
I will help dravit with assistant skills.
