### ISSUE TITLE
[important] Add images to skills 

### ISSUE THREAD

**Issue by dynamitechetan** [fossasia/susi_skill_data#242]
Add images to all the skills. These images are like small icons for skills. 
Try to keep images sqaure, also the images should be free to use. If you are making image yourselves then use a CDN like imgur. 
From now onwards, whenever you make new skills please add description and image icon to them.

**Comment by dynamitechetan** [comment]
I will add images for assistant category.

**Comment by saurabhjn76** [comment]
I will add for problem-solving category

**Comment by DravitLochan** [comment]
will add on entertainment.

**Comment by AliAyub007** [comment]
I will add images for knowledge category.

**Comment by rishiraj824** [comment]
Please mention the exact size as well @dynamitechetan 
Will add all for smalltalk

**Comment by madhavrathi** [comment]
I will help @DravitLochan with first 16 entertainment skills

**Comment by dynamitechetan** [comment]
I don't know the exact size, but images greater than 200x200 should be fine.
We are trying to make something similar to
https://www.amazon.com/alexa-skills/b/ref=nav_shopall_1_ods_ha_con_skills_st?ie=UTF8&node=13727921011
They have used circular images of 210x210 pixels.
So, I thought that finding circular images will be a time-consuming task, so let's use square images and if needed we will make them circular using CSS.
