### ISSUE TITLE
Answer by a specific susi skill overcoming other relevant susi answers

### ISSUE THREAD

**Issue by Manveer695** [fossasia/susi_skill_data#25]
**Actual Behaviour**

To a lot of questions asked to Susi, the answer is coming as "Expression is : NONE (where P:Positive and N:Negative)", due to a skill [here](https://github.com/fossasia/susi_skill_data/blob/master/models/general/knowledge/en/sentiment_analysis.txt). The problem faced is due the question being just a *, instead of something else like "Tell me sentiment analysis of *".

**Screenshots of the issue**

<img width="579" alt="sentimentfail1" src="https://cloud.githubusercontent.com/assets/20307535/26024382/c02d07c0-37ed-11e7-8517-6b4bf667c1ca.PNG">
<img width="575" alt="sentimentfail2" src="https://cloud.githubusercontent.com/assets/20307535/26024383/c0330bb6-37ed-11e7-80ca-d21216278189.PNG">
<img width="575" alt="sentimentfail3" src="https://cloud.githubusercontent.com/assets/20307535/26024384/c03c8fb0-37ed-11e7-9805-b0034f0f62cd.PNG">
and may be many more cases would be there.

**Would you like to work on the issue?**

Yes, I am going to submit a PR related to this, soon.

**Comment by Orbiter** [comment]
fixed with https://github.com/fossasia/susi_skill_data/commit/92159493e630cc9b7ba012eb54b72c3d485d15e4
