### ISSUE TITLE
Update all the skill files as per format defined

### ISSUE THREAD

**Issue by saurabhjn76** [fossasia/susi_skill_data#258]
In reference to the issue: #254 
**Expected Behaviour**

As mentioned in [comment](https://github.com/fossasia/susi_skill_data/issues/254#issuecomment-318995762), update all the skill files as per the following format.
```
::name <Skill_name>
::author <author_name>
::author_url <author_url>
::description <description> 
::dynamic_content <Yes/No>
::developer_privacy_policy <link>
::image <image_url>
::terms_of_use <link>

#Intent
User query1|query2|quer3....
!example:<The question that should be shown in public skill displays>
!expect:<The answer expected for the above example>
Answer for the user query
```

**Would you like to work on the issue?**

This issue needs to be solved collectively, I will contribute too.

**Comment by madhavrathi** [comment]
I will do it for assistant skills.

**Comment by saurabhjn76** [comment]
:+1:  I will add for problem-solving category

**Comment by uday96** [comment]
Will do it for small talk and shopping
