### ISSUE TITLE
Searching feature in Skills CMS

### ISSUE THREAD

**Issue by akash1997** [fossasia/susi_skill_data#293]
**Actual Behaviour**

Selecting a category and language, we need to click the search button to look at that particular category.

**Expected Behavior**

Selecting a category should automatically take you to the particular category. No need to press the search button every time.

**Would you like to work on the issue?**

I am new to Web Development, so it would take some time to understand, but I think I would be able to work on it.

**Comment by saurabhjn76** [comment]
@akash1997 Please close this issue and open it in respective repository here. https://github.com/fossasia/susi_skill_cms/issues  thanks
