### ISSUE TITLE
Example is not correct for the skill

### ISSUE THREAD

**Issue by the-codingninja** [fossasia/susi_skill_data#300]
https://github.com/fossasia/susi_skill_data/blob/e3a18a048a8bb894a5dab37c00961b648fd444c8/models/general/Knowledge/en/atomic.txt#L11

**Comment by sachincool** [comment]
i would like to work on this issue

**Comment by the-codingninja** [comment]
Yes sure go ahead!!

**Comment by gabru-md** [comment]
This issue can now be closed :)
