### ISSUE TITLE
Calculate a+b outputs the product of these numbers

### ISSUE THREAD

**Issue by sayak119** [fossasia/susi_skill_data#314]
**Actual Behaviour**

Wrong answer for additions. It's multiplying as of now.

**Example**

Calculate 2 + 3 yields 6.
Calculate 1 + 100 yields 100.

**Expected Behaviour**

Additions should be done instead of multiplications.

**Steps to reproduce it**

Open chat.susi.ai and type Calculate a + b
where a and b are numbers.

**Screenshots of the issue**

![screenshot from 2018-03-01 06-10-50](https://user-images.githubusercontent.com/28414920/36821348-a6eab954-1d18-11e8-9007-f8e864af54e9.png)

**Would you like to work on the issue?**

Anyone can take up this issue

**Comment by hkedia321** [comment]
Hi @sayak119, this was a client side problem and has been fixed in this PR https://github.com/fossasia/chat.susi.ai/pull/1105. I think we can close this issue. Thanks.

**Comment by sayak119** [comment]
Yup closing it now.
