### ISSUE TITLE
SUSI only understands a proper framed question instead of an informal question

### ISSUE THREAD

**Issue by prateekiiest** [fossasia/susi_skill_data#324]
**Actual Behaviour**
Me : 'What is your name?'
SUSI : Hi my name is SUSI

Me : Your name?
SUSI : Sorry I cannot understand you

Please state here what is currently happening.
If the question is framed only with proper verbs and all, then only SUSI gives a correct answer , otherwise not as shown above.

**Expected Behaviour**
Me : 'What is your name?'
SUSI : Hi my name is SUSI

Me : Your name?
SUSI : Hi my name is SUSI

State here what the feature should enable the user to do.
Any word with a question mark, it should return a proper answer to it.

**Steps to reproduce it**
Adding a new skill

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.

**Would you like to work on the issue?**

Yes

Please let us know if you can work on it or the issue should be assigned to someone else.

Yes

**Comment by prateekiiest** [comment]
Added skill to SUSI Skill CMS

**Comment by mariobehling** [comment]
If you open an issue here now, then you don't understand the architecture of SUSI.AI. Logic is implemented a) in the server and b) in specific skills. Skills are edited on the Skills CMS.
