### ISSUE TITLE
Skill Farming makes bold statement

### ISSUE THREAD

**Issue by tabesin** [fossasia/susi_skill_data#351]
**Actual Behaviour**

The current farming skill:
When it will rain
!example:When it will rain
It will rain after two days

**Expected Behaviour**

This cannot be predicted without a weather forecast and it is bad style to forecast this in a skill.

**Comment by atm1504** [comment]
<img width="367" alt="Screenshot 2019-07-17 at 9 34 55 AM" src="https://user-images.githubusercontent.com/43731599/61346392-2c0a7180-a876-11e9-9def-46862ecef9f5.png">

@mariobehling please close it. I have updated the skill data

**Comment by atm1504** [comment]
@akshatnitd @Orbiter please close it. I have already resolved it.

**Comment by tabesin** [comment]
Thank you
