### ISSUE TITLE
Skill: good morning

### ISSUE THREAD

**Issue by tabesin** [fossasia/susi_skill_data#359]
**Actual Behaviour**

![goddmorning](https://user-images.githubusercontent.com/10114907/61231215-fa858f00-a72b-11e9-8e08-ba90ff0d75cb.png)

**Expected Behaviour**

- [ ] Susi answers the greeting appropriately.

- [ ]  Susi is able to communicate depending on the context morning and add small talk.

- [ ] Susi recognises that the question was not asked in the morning and wonders about the time zone setting.

**Comment by atm1504** [comment]
<img width="369" alt="Screenshot 2019-07-31 at 6 18 49 PM" src="https://user-images.githubusercontent.com/43731599/62213067-bf3bbf00-b3bf-11e9-9750-5faa9847eef2.png">

@mariobehling please close it. I have added the skill.
