### ISSUE TITLE
Incorrect responses to 'When' query

### ISSUE THREAD

**Issue by Laughing-Boy** [fossasia/susi_skill_data#57]
<img width="800" alt="when2" src="https://cloud.githubusercontent.com/assets/24853337/26634509/8a944254-4634-11e7-8be8-8af0160a647f.png">
<img width="764" alt="when3" src="https://cloud.githubusercontent.com/assets/24853337/26634549/ac48a462-4634-11e7-849b-58c7d365e31d.png">

**Comment by isuruAb** [comment]
@hpdang  this issue can be closed
